@PrepApi_HostAddress = http://localhost:5053
@Bearer_Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Iml2YW5yIiwic3ViIjoiaXZhbnIiLCJqdGkiOiJhMTg4OTUzZSIsImF1ZCI6InByZXAtYXBpIiwibmJmIjoxNzQ1NTc5MjAzLCJleHAiOjE3NTM0NDE2MDMsImlhdCI6MTc0NTU3OTIwNCwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.M5TynhpTB2uyyIXE8jOpWWOhWurrGrJ2ovJX1zxwKD8

###
### Recipe Endpoints
###

### Create a recipe
POST {{PrepApi_HostAddress}}/api/recipes/
Content-Type: application/json
Authorization: Bearer {{Bearer_Token}}

{
  "name": "Simple Recipe",
  "description": "Basic recipe description.",
  "prepTimeMinutes": 5,
  "cookTimeMinutes": 10,
  "yield": "8 servings",
  "steps": [
    { "description": "Mix dry ingredients.", "order": 1 },
    { "description": "Add wet ingredients.", "order": 2 },
    { "description": "Cook until done.", "order": 3 }
  ],
  "ingredients": [
    {
      "ingredientId": "11111111-1111-1111-1111-111111111111",
      "quantity": 2,
      "unit": 1
    },
    {
      "ingredientId": "22222222-2222-2222-2222-222222222222",
      "quantity": 3,
      "unit": 2
    }
  ],
  "tagIds": ["02ae13d8-da46-4176-a786-624bb488c7dc"]
}

### Get a recipe
GET {{PrepApi_HostAddress}}/api/recipes/0196bbe2-c076-7f21-8716-80b4083756f6
Authorization: Bearer {{Bearer_Token}}

### Update a recipe
PUT {{PrepApi_HostAddress}}/api/recipes/0196bbe2-c076-7f21-8716-80b4083756f6
Content-Type: application/json
Authorization: Bearer {{Bearer_Token}}

{
  "name": "Updated Recipe",
  "description": "Updated recipe description.",
  "prepTimeMinutes": 1,
  "cookTimeMinutes": 1,
  "yield": "1 servings",
  "steps": [
    { "description": "Combine ingredients.", "order": 1 },
    { "description": "Mix thoroughly.", "order": 2 }
  ],
  "ingredients": [
    {
      "ingredientId": "11111111-1111-1111-1111-111111111111",
      "quantity": 3,
      "unit": 1
    },
    {
      "ingredientId": "33333333-3333-3333-3333-333333333333",
      "quantity": 4,
      "unit": 2
    }
  ],
  "tagIds": []
}

### Delete a recipe
DELETE {{PrepApi_HostAddress}}/api/recipes/0196a205-6f27-70b1-adfc-92476f0f8bf3
Authorization: Bearer {{Bearer_Token}}

### Create a variant from a prep
POST {{PrepApi_HostAddress}}/api/recipes/0196c109-9e35-7345-ab89-40dc7b52eaa4/variants
Content-Type: application/json
Authorization: Bearer {{Bearer_Token}}

{
  "name": "My New Variant Recipe",
  "setAsFavorite": true
}

### Set a recipe variant as favorite
PUT {{PrepApi_HostAddress}}/api/recipes/55555555-5555-5555-5555-555555555555/favorite
Authorization: Bearer {{Bearer_Token}}

###
### Prep Endpoints
###

### Create a Prep
POST {{PrepApi_HostAddress}}/api/preps/
Content-Type: application/json
Authorization: Bearer {{Bearer_Token}}

{
  "recipeId": "55555555-5555-5555-5555-555555555555",
  "summaryNotes": "Changed ingredients.",
  "prepTimeMinutes": 12,
  "cookTimeMinutes": 18,
  "steps": [
    { "description": "Combine ingredients.", "order": 1 },
    { "description": "Mix thoroughly.", "order": 2 },
    { "description": "Rest.", "order": 3 }
  ],
  "prepIngredients": [
    {
      "ingredientId": "11111111-1111-1111-1111-111111111111",
      "quantity": 3,
      "unit": 1,
      "notes": "Simple note"
    },
    {
      "ingredientId": "22222222-2222-2222-2222-222222222222",
      "quantity": 3,
      "unit": 2
    },
    {
      "ingredientId": "44444444-4444-4444-4444-444444444444",
      "quantity": 3,
      "unit": 2
    }
  ]
}

### Delete a prep
DELETE {{PrepApi_HostAddress}}/api/preps/0196a205-6f27-70b1-adfc-92476f0f8bf3
Authorization: Bearer {{Bearer_Token}}

### Get a prep
GET {{PrepApi_HostAddress}}/api/preps/0196a20b-e844-7ee5-ad5f-8518f5a586f1
Authorization: Bearer {{Bearer_Token}}

### Get preps by recipe ID (paginated and sorted)
GET {{PrepApi_HostAddress}}/api/preps/recipe/55555555-5555-5555-5555-555555555555?pageSize=10&pageIndex=0&sortorder=desc
Authorization: Bearer {{Bearer_Token}}

### Update a Prep
PUT {{PrepApi_HostAddress}}/api/preps/0196b160-61d1-7f8c-82db-9fd6c1c17111
Content-Type: application/json
Authorization: Bearer {{Bearer_Token}}

{
  "summaryNotes": "Updated prep notes and slightly different ingredients.",
  "prepTimeMinutes": 15,
  "cookTimeMinutes": 25,
  "steps": [
    { "description": "Prepare all ingredients as per new instructions.", "order": 1 },
    { "description": "Combine in a large bowl.", "order": 2 },
    { "description": "Cook for 25 minutes.", "order": 3 }
  ],
  "prepIngredients": [
    {
      "ingredientId": "11111111-1111-1111-1111-111111111111",
      "quantity": 2,
      "unit": 1,
      "notes": "Reduced quantity"
    },
    {
      "ingredientId": "33333333-3333-3333-3333-333333333333",
      "quantity": 1,
      "unit": 3,
      "notes": "Added new ingredient"
    }
  ]
}

###
### Tag Endpoints
###

### Create a new tag
POST {{PrepApi_HostAddress}}/api/tags
Content-Type: application/json
Authorization: Bearer {{Bearer_Token}}

{
  "name": "Quick  2"
}

### Get tags with search term
GET {{PrepApi_HostAddress}}/api/tags?term=quick
Authorization: Bearer {{Bearer_Token}}

### Update an existing tag
PUT {{PrepApi_HostAddress}}/api/tags/0196c01a-649e-7ceb-aa8a-aeb685bfa0d0
Content-Type: application/json
Authorization: Bearer {{Bearer_Token}}

{
  "name": "Very Quick Meafl"
}

### Delete a tag
DELETE {{PrepApi_HostAddress}}/api/tags/0196c01a-649e-7ceb-aa8a-aeb685bfa0d0
Authorization: Bearer {{Bearer_Token}}